import { ContractChecklist } from "./types";

export const checklistNajemInstytucjonalny: ContractChecklist = {
  contractType: "najem_instytucjonalny",
  title: "Checklista: Najem instytucjonalny lokalu",
  description:
    "Checklista weryfikacji umowy najmu instytucjonalnego zawieranej przez przedsiębiorcę z konsumentem (art. 19f–19k Ustawy o ochronie praw lokatorów).",
  version: "2026.10-draft",
  items: [
    {
      id: "instytucjonalny-status-wynajmujacego",
      contractType: "najem_instytucjonalny",
      area: "Status stron",
      controlQuestion: "Czy wynajmujący jest przedsiębiorcą prowadzącym działalność w zakresie wynajmu lokali?",
      redCriteria: "Zawarcie umowy najmu instytucjonalnego przez osobę prywatną nieprowadzącą działalności gospodarczej.",
      yellowCriteria: "Brak wskazania numeru NIP/KRS i wpisu w CEIDG/KRS w przedmiocie wynajmu nieruchomości.",
      greenCriteria: "Wynajmujący jest osobą fizyczną, prawną lub jednostką organizacyjną prowadzącą działalność gospodarczą w zakresie wynajmowania lokali (art. 19f ust. 1).",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Najem instytucjonalny może zawierać wyłącznie przedsiębiorca wynajmujący lokale w ramach działalności.",
      kbSourceIds: ["uopl-art-19f"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "instytucjonalny-oswiadczenie-notarialne",
      contractType: "najem_instytucjonalny",
      area: "Załączniki i rygor egzekucji",
      controlQuestion: "Czy załączono oświadczenie notarialne o poddaniu się egzekucji bez wskazywania lokalu zastępczego?",
      redCriteria: "Żądanie od najemcy wskazania innego lokalu zastępczego lub zgody osoby trzeciej (w najmie instytucjonalnym ustawowo nie jest to wymagane).",
      yellowCriteria: "Zbyt krótki termin na dostarczenie aktu notarialnego.",
      greenCriteria: "Oświadczenie w formie aktu notarialnego o poddaniu się egzekucji z art. 777 kpc bez konieczności wskazywania lokalu zastępczego (art. 19g ust. 1).",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Brak oświadczenia notarialnego pozbawia umowę waloru najmu instytucjonalnego.",
      kbSourceIds: ["uopl-art-19g"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "instytucjonalny-kaucja-limit-6x",
      contractType: "najem_instytucjonalny",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy kaucja nie przekracza limitu 6-krotności miesięcznego czynszu?",
      redCriteria: "Kaucja przekracza 6-krotność miesięcznego czynszu (art. 19h ust. 1 UoPL).",
      yellowCriteria: "Kaucja wyższa niż 2-krotność miesięcznego czynszu.",
      greenCriteria: "Kaucja zabezpieczająca mieści się w ustawowym limicie do 6-krotności czynszu.",
      missingIsRisk: false,
      missingSeverity: "none",
      benchmarkParam: "kaucja_wielokrotnosc_czynszu",
      kbSourceIds: ["uopl-art-19h"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "instytucjonalny-kaucja-zaspokojenie-biezace",
      contractType: "najem_instytucjonalny",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy uregulowano zasady zaspokajania roszczeń z kaucji w trakcie trwania umowy?",
      redCriteria: "Potrącanie z kaucji kwot spornych bez wezwania do zapłaty i bez przedstawienia rozliczenia.",
      yellowCriteria: "Obowiązek uzupełnienia kaucji w zbyt krótkim terminie (poniżej 7 dni).",
      greenCriteria: "Zaspokojenie roszczeń z kaucji w trakcie najmu po uprzednim wezwaniu z terminem min. 7 dni na uzupełnienie (art. 19h ust. 2).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-19h"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "instytucjonalny-wypowiedzenie-opróżnienie-termin",
      contractType: "najem_instytucjonalny",
      area: "Rozwiązanie umowy i egzekucja",
      controlQuestion: "Czy termin na opróżnienie lokalu po wygaśnięciu umowy wynosi co najmniej 14 dni?",
      redCriteria: "Wyznaczenie terminu na opróżnienie lokalu krótszego niż 14 dni od doręczenia żądania (sprzeczność z art. 19i ust. 3 UoPL).",
      yellowCriteria: "Niejasny tryb doręczania pisemnego żądania opróżnienia lokalu z urzędowo poświadczonym podpisem.",
      greenCriteria: "Pisemne żądanie opróżnienia lokalu z podpisem notarialnie poświadczonym wyznacza termin nie krótszy niż 14 dni od doręczenia.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-19i"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "instytucjonalny-klauzule-abuzywne-b2c",
      contractType: "najem_instytucjonalny",
      area: "Ochrona konsumencka",
      controlQuestion: "Czy wzorzec umowny przedsiębiorcy nie zawiera klauzul abuzywnych wobec konsumenta?",
      redCriteria: "Zastrzeżenie jednostronnej zmiany regulaminu budynku, arbitralnych kar umownych lub wyłączenia rękojmi za wady.",
      yellowCriteria: "Narzucenie właściwości sądu siedziby wynajmującego zamiast sądu miejsca położenia nieruchomości.",
      greenCriteria: "Wzorzec umowy pozbawiony klauzul z art. 385³ k.c. i rejestru UOKiK.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["4991", "2487", "2045"],
      courtRulingSignatures: ["C-229/19"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
