import { ContractChecklist } from "./types";

export const checklistNajemLokaluMieszkalnego: ContractChecklist = {
  contractType: "najem_lokalu_mieszkalnego",
  title: "Checklista: Najem lokalu mieszkalnego (zwykły)",
  description:
    "Kompleksowa checklista weryfikacji umowy najmu lokalu mieszkalnego zawartej na gruncie Kodeksu cywilnego i Ustawy o ochronie praw lokatorów.",
  version: "2026.10-draft",
  items: [
    // --------------------------------------------------------------------------
    // OBSZAR 1: KAUCJA I ZABEZPIECZENIA
    // --------------------------------------------------------------------------
    {
      id: "najem-kaucja-limit",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy wysokość kaucji mieści się w ustawowym limicie?",
      redCriteria: "Kaucja przekracza 12-krotność miesięcznego czynszu za lokal (sprzeczność z art. 6 ust. 1 UoPL).",
      yellowCriteria: "Kaucja przekracza 2-krotność miesięcznego czynszu (odbiega od standardu rynkowego 1-krotności).",
      greenCriteria: "Kaucja wynosi równowartość 1 lub 2-miesięcznego czynszu.",
      missingIsRisk: false,
      missingSeverity: "none",
      benchmarkParam: "kaucja_wielokrotnosc_czynszu",
      kbSourceIds: ["uopl-art-6"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-kaucja-termin-zwrotu",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy termin zwrotu kaucji nie przekracza ustawowego terminu 1 miesiąca?",
      redCriteria:
        "Termin zwrotu kaucji jest dłuższy niż miesiąc od opróżnienia lokalu lub zwrot uzależniono od niepewnych zdarzeń przyszłych.",
      yellowCriteria: "Brak jednoznacznego terminu zwrotu kaucji w treści umowy.",
      greenCriteria: "Kaucja podlega zwrotowi w terminie do 30 dni od dnia zdania lokalu i spisania protokołu.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak terminu w umowie oznacza konieczność powoływania się na art. 6 ust. 4 UoPL.",
      kbSourceIds: ["uopl-art-6"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-kaucja-przepadek",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy umowa nie zawiera klauzuli bezwarunkowego przepadku kaucji?",
      redCriteria:
        "Zastrzeżenie przepadku kaucji w całości w razie wcześniejszego rozwiązania umowy lub jako zryczałtowanej kary umownej.",
      yellowCriteria: "Zapis o potrąceniu z kaucji kar umownych bez konieczności udowodnienia realnej szkody.",
      greenCriteria: "Kaucja służy wyłącznie pokryciu udokumentowanych zaległości czynszowych i szkód przekraczających normalne zużycie.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-6", "kc-art-385-1"],
      uokikClauseNumbers: ["2045"],
      courtRulingSignatures: ["III CZP 52/19"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-kaucja-waloryzacja",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Kaucja i zabezpieczenia",
      controlQuestion: "Czy zapewniono ustawową waloryzację kaucji przy zwrocie?",
      redCriteria: "Wyłączenie prawa najemcy do waloryzacji kaucji przy wzroście stawki czynszu (sprzeczność z art. 6 ust. 3 UoPL).",
      yellowCriteria: "Brak wzmianki o waloryzacji kaucji.",
      greenCriteria: "Zwrot kaucji w kwocie zwaloryzowanej według stawki czynszu z dnia zwrotu, nie niższej niż pobrana.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-6"],
      lawyerReviewStatus: "draft",
      version: 1,
    },

    // --------------------------------------------------------------------------
    // OBSZAR 2: CZAS TRWANIA I WYPOWIEDZENIE
    // --------------------------------------------------------------------------
    {
      id: "najem-wypowiedzenie-katalog-przyczyn",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czas trwania i wypowiedzenie",
      controlQuestion: "Czy przyczyny wypowiedzenia przez wynajmującego są zgodne z ustawą?",
      redCriteria:
        "Przyznanie wynajmującemu prawa do wypowiedzenia umowy z przyczyn niewymienionych w art. 11 UoPL lub z zachowaniem skróconego terminu (np. 7 lub 14 dni).",
      yellowCriteria: "Niejasno zdefiniowane przyczyny rozwiązania umowy.",
      greenCriteria: "Wypowiedzenie przez wynajmującego wyłącznie na zasadach i w terminach określonych w art. 11 UoPL.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-11"],
      courtRulingSignatures: ["III CZP 11/13"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-wypowiedzenie-zaleglosc-czynszowa",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czas trwania i wypowiedzenie",
      controlQuestion: "Czy wypowiedzenie za zaległości wymaga pisemnego uprzedzenia i terminu miesięcznego?",
      redCriteria:
        "Zezwolenie na natychmiastowe wypowiedzenie umowy za zaległość za 1 miesiąc lub bez uprzedzenia na piśmie z dodatkowym 1-miesięcznym terminem.",
      yellowCriteria: "Zapis o wypowiedzeniu z powodu zaległości bez sprecyzowania procedury ostrzegawczej.",
      greenCriteria:
        "Wypowiedzenie dopuszczalne dopiero przy zwłoce za 3 pełne okresy płatności i po bezskutecznym upływie dodatkowego 1-miesięcznego terminu wyznaczonego na piśmie.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-11"],
      uokikClauseNumbers: ["592"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-czas-oznaczony-wazne-przyczyny",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czas trwania i wypowiedzenie",
      controlQuestion: "W umowie na czas oznaczony: czy precyzyjnie określono ważne przyczyny wypowiedzenia?",
      redCriteria:
        "Zastrzeżenie w umowie na czas oznaczony prawa do wypowiedzenia 'z ważnych przyczyn' bez ich wymienienia lub bez podania jakiejkolwiek przyczyny.",
      yellowCriteria: "Katalog przyczyn wypowiedzenia na czas oznaczony jest sformułowany zbyt ogólnikowo.",
      greenCriteria: "Wymieniono zamknięty, precyzyjny katalog obiektywnych zdarzeń uprawniających najemcę do wcześniejszego wypowiedzenia (np. utrata pracy, relokacja).",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak wskazania przyczyn uniemożliwia najemcy wcześniejsze rozwiązanie umowy na czas oznaczony (art. 673 § 3 k.c.).",
      kbSourceIds: ["kc-art-673"],
      courtRulingSignatures: ["V CSK 31/08"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-termin-wypowiedzenia-lokalu",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czas trwania i wypowiedzenie",
      controlQuestion: "W umowie na czas nieoznaczony: czy termin wypowiedzenia wynosi min. 3 miesiące?",
      redCriteria: "Termin wypowiedzenia przez wynajmującego krótszy niż 3 miesiące naprzód na koniec miesiąca kalendarzowego.",
      yellowCriteria: "Termin wypowiedzenia dla najemcy krótszy niż 1 miesiąc bez ważnej przyczyny.",
      greenCriteria: "Termin wypowiedzenia wynosi co najmniej 3 miesiące naprzód na koniec miesiąca kalendarzowego.",
      missingIsRisk: false,
      missingSeverity: "none",
      benchmarkParam: "termin_wypowiedzenia_miesiace",
      kbSourceIds: ["kc-art-688"],
      lawyerReviewStatus: "draft",
      version: 1,
    },

    // --------------------------------------------------------------------------
    // OBSZAR 3: CZYNSZ, OPŁATY I MEDIA
    // --------------------------------------------------------------------------
    {
      id: "najem-podwyzka-czynszu-procedura",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czynsz, opłaty i media",
      controlQuestion: "Czy zasady podwyższania czynszu spełniają rygory ustawowe?",
      redCriteria:
        "Prawo wynajmującego do jednostronnej podwyżki czynszu w dowolnym czasie ze skutkiem natychmiastowym lub krótszym niż 3 miesiące.",
      yellowCriteria: "Zastrzeżenie automatycznej podwyżki czynszu bez odwołania do oficjalnego wskaźnika inflacji GUS.",
      greenCriteria:
        "Wypowiedzenie dotychczasowej wysokości czynszu na piśmie pod rygorem nieważności z zachowaniem terminu 3 miesięcy i uzasadnieniem kalkulacji.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-8a", "kc-art-685-1"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-oplaty-niezalezne-rozliczenie",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czynsz, opłaty i media",
      controlQuestion: "Czy opłaty za media rozliczane są według faktycznych kosztów bez narzutu?",
      redCriteria: "Pobieranie opłat dodatkowych i prowizji manipulacyjnych za rozliczenie mediów przez wynajmującego.",
      yellowCriteria: "Brak obowiązku przedstawiania najemcy rachunków i faktur od dostawców mediów do wglądu.",
      greenCriteria: "Opłaty eksploatacyjne i zaliczki rozliczane ściśle według faktur dostawców i wskazań liczników.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak procedury rozliczenia rodzi spory co do wysokości faktycznie zużytych mediów.",
      kbSourceIds: ["uopl-art-9"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-kara-umowna-opoznienie",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Czynsz, opłaty i media",
      controlQuestion: "Czy umowa nie nakłada kary umownej za nieterminową zapłatę czynszu?",
      redCriteria:
        "Kara umowna kwotowa lub procentowa za każdy dzień opóźnienia w zapłacie czynszu (naruszenie art. 483 § 1 k.c., dopuszczalne są wyłącznie odsetki).",
      yellowCriteria: "Odsetki za opóźnienie wyższe niż ustawowe odsetki maksymalne za opóźnienie (art. 359 § 2[1] k.c.).",
      greenCriteria: "W razie opóźnienia w płatności czynszu wynajmującemu przysługują wyłącznie odsetki ustawowe za opóźnienie.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-3"],
      uokikClauseNumbers: ["2487"],
      lawyerReviewStatus: "draft",
      version: 1,
    },

    // --------------------------------------------------------------------------
    // OBSZAR 4: NAPRAWY, NAKŁADY I PROTOKÓŁ
    // --------------------------------------------------------------------------
    {
      id: "najem-protokol-zdawczo-odbiorczy",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Naprawy, nakłady i protokół",
      controlQuestion: "Czy umowa przewiduje sporządzenie protokołu zdawczo-odbiorczego?",
      redCriteria: "Oświadczenie najemcy, że lokal jest w stanie idealnym, bez faktycznego sporządzenia protokołu i spisu liczników.",
      yellowCriteria: "Brak wzmianki o protokole przy zwrocie lokalu.",
      greenCriteria: "Wymóg sporządzenia szczegółowego protokołu zdawczo-odbiorczego ze stanem wyposażenia i liczników przed wydaniem i przy zwrocie.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak protokołu uniemożliwia obronę najemcy przed zarzutem uszkodzenia lokalu powstałego wcześniej.",
      kbSourceIds: ["uopl-art-6c", "kc-art-675"],
      courtRulingSignatures: ["III CZP 52/19"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-naprawy-podzial-obowiazkow",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Naprawy, nakłady i protokół",
      controlQuestion: "Czy podział obowiązków w zakresie napraw odpowiada przepisom prawa?",
      redCriteria: "Obciążenie najemcy wszelkimi naprawami lokalu, w tym naprawami instalacji w ścianach, wymianą pieca czy okien.",
      yellowCriteria: "Niejasny podział kosztów napraw drobnych i napraw substancji lokalu.",
      greenCriteria:
        "Wynajmujący odpowiada za instalacje i naprawy główne budynku (art. 6a UoPL); najemca za konserwację i drobne naprawy bieżące (art. 6b UoPL).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-6a", "uopl-art-6b", "kc-art-662", "kc-art-663", "kc-art-681"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-wylaczenie-rekojmi",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Naprawy, nakłady i protokół",
      controlQuestion: "Czy umowa nie wyłącza uprawnień najemcy z tytułu rękojmi za wady lokalu?",
      redCriteria: "Zrzeczenie się przez najemcę prawa do żądania obniżenia czynszu z powodu wad lokalu uniemożliwiających korzystanie.",
      yellowCriteria: "Wyłączenie odpowiedzialności wynajmującego za awarie niezależne od najemcy.",
      greenCriteria: "Najemcy przysługuje prawo żądania naprawy wad, obniżenia czynszu lub natychmiastowego rozwiązania umowy w razie wad zagrażających zdrowiu.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-664", "kc-art-385-1"],
      uokikClauseNumbers: ["6124"],
      lawyerReviewStatus: "draft",
      version: 1,
    },

    // --------------------------------------------------------------------------
    // OBSZAR 5: PRAWA LOKATORA I WIZYTY WŁAŚCICIELA
    // --------------------------------------------------------------------------
    {
      id: "najem-wizyty-wlasciciela-inspekcja",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Prawa lokatora i wizyty właściciela",
      controlQuestion: "Czy wizyty właściciela w lokalu wymagają obecności i uprzedzenia najemcy?",
      redCriteria: "Prawo wejścia wynajmującego do lokalu w dowolnym czasie pod nieobecność najemcy z użyciem własnych kluczy (klauzula abuzywna).",
      yellowCriteria: "Wizyty z krótkim uprzedzeniem (np. 1 godzina naprzód) bez uzasadnienia awarią.",
      greenCriteria: "Wizyty wyłącznie w obecności najemcy, w terminie uzgodnionym z wyprzedzeniem co najmniej 24-48 godzin (z wyjątkiem nagłej awarii).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1"],
      uokikClauseNumbers: ["4991"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "najem-zakazy-niedozwolone",
      contractType: "najem_lokalu_mieszkalnego",
      area: "Prawa lokatora i wizyty właściciela",
      controlQuestion: "Czy umowa nie narusza dóbr osobistych i praw konsumenta (dzieci, goście, zwierzęta)?",
      redCriteria: "Bezwzględny zakaz przyjmowania gości lub zamieszkania z nowonarodzonym dzieckiem pod rygorem natychmiastowego wyrzucenia.",
      yellowCriteria: "Całkowity zakaz trzymania zwierząt domowych pod rygorem wygórowanej kary umownej.",
      greenCriteria: "Zasady korzystania z lokalu zgodne z poszanowaniem miru domowego i dóbr osobistych lokatora.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "uopl-art-2"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
