import { ContractChecklist } from "./types";

export const checklistNajemLokaluUzytkowego: ContractChecklist = {
  contractType: "najem_lokalu_uzytkowego",
  title: "Checklista: Najem lokalu użytkowego (komercyjny)",
  description:
    "Checklista weryfikacji umowy najmu lokalu użytkowego/komercyjnego pod kątem ryzyk dla najemcy-przedsiębiorcy na gruncie Kodeksu cywilnego.",
  version: "2026.10-draft",
  items: [
    {
      id: "uzytkowy-przeznaczenie-lokalu",
      contractType: "najem_lokalu_uzytkowego",
      area: "Przedmiot i przeznaczenie",
      controlQuestion: "Czy precyzyjnie określono profil dozwolonej działalności gospodarczej?",
      redCriteria: "Zakaz prowadzenia zamierzonej przez najemcę działalności lub brak zapewnienia o zgodzie na przeznaczenie lokalu.",
      yellowCriteria: "Zbyt wąski katalog dozwolonych usług uniemożliwiający rozszerzenie oferty firmy.",
      greenCriteria: "Jednoznaczne potwierdzenie prawa do prowadzenia oznaczonej działalności gospodarczej wraz z infrastrukturą.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Niedookreślone przeznaczenie może prowadzić do zarzutu używania rzeczy sprzecznie z umową (art. 666 k.c.).",
      kbSourceIds: ["kc-art-659", "kc-art-666"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uzytkowy-wypowiedzenie-zaleglosc-art-687",
      contractType: "najem_lokalu_uzytkowego",
      area: "Rozwiązanie i wypowiedzenie",
      controlQuestion: "Czy wypowiedzenie z powodu zwłoki w zapłacie czynszu spełnia rygor art. 687 k.c.?",
      redCriteria: "Prawo natychmiastowego rozwiązania umowy za kilkudniowe opóźnienie w zapłacie czynszu bez uprzedzenia na piśmie.",
      yellowCriteria: "Skrócenie dodatkowego terminu na spłatę zaległości poniżej 1 miesiąca.",
      greenCriteria:
        "Wypowiedzenie bez zachowania terminów dopuszczalne wyłącznie przy zwłoce za co najmniej dwa pełne okresy płatności i po uprzedzeniu na piśmie z udzieleniem dodatkowego terminu miesięcznego (art. 687 k.c.).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-687"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uzytkowy-czas-oznaczony-przyczyny-wypowiedzenia",
      contractType: "najem_lokalu_uzytkowego",
      area: "Rozwiązanie i wypowiedzenie",
      controlQuestion: "W umowie na czas oznaczony: czy precyzyjnie określono okoliczności uprawniające do wypowiedzenia?",
      redCriteria: "Zastrzeżenie wypowiedzenia 'z ważnych przyczyn' bez ich skonkretyzowania (nieważność zapisu wg art. 673 § 3 k.c.).",
      yellowCriteria: "Jednostronne prawo do wypowiedzenia przysługujące wyłącznie wynajmującemu.",
      greenCriteria: "Symetryczne, precyzyjnie zdefiniowane przesłanki wcześniejszego wypowiedzenia dla obu stron umowy.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak wskazania przyczyn oznacza brak możliwości wcześniejszego rozwiązania wieloletniego najmu komercyjnego.",
      kbSourceIds: ["kc-art-673"],
      courtRulingSignatures: ["V CSK 31/08"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uzytkowy-naklady-adaptacja-zwrot",
      contractType: "najem_lokalu_uzytkowego",
      area: "Nakłady i modernizacja",
      controlQuestion: "Czy zasady adaptacji lokalu i rozliczenia nakładów po zakończeniu najmu są uregulowane?",
      redCriteria: "Obowiązek pozostawienia wszelkich nakładów i ulepszeń bez jakiegokolwiek wynagrodzenia i bez prawa do ich zdemontowania.",
      yellowCriteria: "Konieczność przywrócenia stanu pierwotnego (usunięcia nakładów) na wyłączny koszt najemcy w nierealnym terminie.",
      greenCriteria: "Jasno określone prawo do amortyzacji nakładów, prawo do demontażu instalacji (art. 684 k.c.) lub zasady odkupu ulepszeń.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Brak regulacji rodzi wysokie ryzyko utraty nakładów inwestycyjnych poniesionych na przystosowanie lokalu.",
      kbSourceIds: ["kc-art-675", "kc-art-677", "kc-art-684"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uzytkowy-kaucja-gwarancja-bankowa",
      contractType: "najem_lokalu_uzytkowego",
      area: "Zabezpieczenia finansowe",
      controlQuestion: "Czy zasady uruchomienia i zwrotu kaucji lub gwarancji bankowej są precyzyjnie określone?",
      redCriteria: "Zastrzeżenie bezwarunkowego przepadku kaucji lub prawa żądania wypłaty z gwarancji na pierwsze żądanie bez wykazania naruszenia.",
      yellowCriteria: "Termin zwrotu kaucji dłuższy niż 30 dni od protokolarnego zwrotu lokalu.",
      greenCriteria: "Zaspokojenie z kaucji/gwarancji możliwe wyłącznie po bezskutecznym wezwaniu do usunięcia naruszenia i zwrot w ciągu 14-30 dni.",
      missingIsRisk: false,
      missingSeverity: "none",
      benchmarkParam: "kaucja_wielokrotnosc_czynszu",
      kbSourceIds: ["kc-art-659"],
      courtRulingSignatures: ["III CZP 52/19"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
