import { ContractChecklist } from "./types";

export const checklistNajemOkazjonalny: ContractChecklist = {
  contractType: "najem_okazjonalny",
  title: "Checklista: Najem okazjonalny lokalu",
  description:
    "Specjalistyczna checklista weryfikacji umowy najmu okazjonalnego lokalu mieszkalnego (art. 19a–19e Ustawy o ochronie praw lokatorów).",
  version: "2026.10-draft",
  items: [
    {
      id: "okazjonalny-status-wynajmujacego",
      contractType: "najem_okazjonalny",
      area: "Wymogi formalne najmu okazjonalnego",
      controlQuestion: "Czy wynajmujący jest osobą fizyczną nieprowadzącą działalności w zakresie najmu?",
      redCriteria: "Wynajmujący zawiera umowę jako spółka lub w ramach działalności gospodarczej (wówczas właściwy jest najem instytucjonalny).",
      yellowCriteria: "Brak oświadczenia o statusie właściciela nieprowadzącego działalności w zakresie najmu.",
      greenCriteria: "Wynajmujący jest osobą fizyczną nieprowadzącą działalności gospodarczej w zakresie wynajmowania lokali (art. 19a ust. 1).",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Podmiot gospodarczy nie może skutecznie zawrzeć najmu okazjonalnego — grozi to zakwalifikowaniem jako najem zwykły.",
      kbSourceIds: ["uopl-art-19a"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-oswiadczenie-notarialne-777",
      contractType: "najem_okazjonalny",
      area: "Załączniki i rygor egzekucji",
      controlQuestion: "Czy określono obowiązek dostarczenia oświadczenia notarialnego o poddaniu się egzekucji?",
      redCriteria: "Narzucenie najemcy pokrycia 100% kosztów aktu notarialnego bez wcześniejszego uzgodnienia lub żądanie rygoru wykraczającego poza opróżnienie lokalu.",
      yellowCriteria: "Zbyt krótki termin na dostarczenie oświadczenia notarialnego (poniżej 7 dni od podpisania umowy).",
      greenCriteria: "Do umowy dołączono oświadczenie w formie aktu notarialnego o poddaniu się egzekucji i zobowiązaniu do opróżnienia i wydania lokalu (art. 777 § 1 pkt 4 kpc).",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Brak oświadczenia notarialnego powoduje, że najem okazjonalny nie wywołuje skutków prawnych i traktowany jest jak najem zwykły.",
      kbSourceIds: ["uopl-art-19a"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-wskazanie-lokalu-zastepczego",
      contractType: "najem_okazjonalny",
      area: "Załączniki i rygor egzekucji",
      controlQuestion: "Czy załączono wskazanie przez najemcę innego lokalu, w którym będzie mógł zamieszkać?",
      redCriteria: "Brak wskazania lokalu zastępczego przy jednoczesnym wymaganiu oświadczenia notarialnego.",
      yellowCriteria: "Brak klauzuli zobowiązującej najemcę do wskazania innego lokalu w terminie 21 dni w razie utraty możliwości zamieszkania.",
      greenCriteria: "Dołączono oświadczenie najemcy wskazujące inny lokal, w którym będzie mógł zamieszkać w przypadku wykonania egzekucji.",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Obligatoryjny załącznik ustawowy z art. 19a ust. 2 pkt 2 UoPL.",
      kbSourceIds: ["uopl-art-19a"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-zgoda-wlasciciela-lokalu",
      contractType: "najem_okazjonalny",
      area: "Załączniki i rygor egzekucji",
      controlQuestion: "Czy dołączono zgodę właściciela lokalu zastępczego z notarialnie poświadczonym podpisem?",
      redCriteria: "Zgoda właściciela lokalu zastępczego sporządzona w zwykłej formie pisemnej (brak poświadczenia notarialnego podpisu).",
      yellowCriteria: "Nieprecyzyjnie oznaczony właściciel lokalu zastępczego (brak numeru księgi wieczystej).",
      greenCriteria: "Załączono oświadczenie właściciela lokalu lub osoby posiadającej tytuł prawny, z podpisem notarialnie poświadczonym.",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Wymóg art. 19a ust. 2 pkt 3 UoPL.",
      kbSourceIds: ["uopl-art-19a"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-kaucja-limit-6x",
      contractType: "najem_okazjonalny",
      area: "Kaucja w najmie okazjonalnym",
      controlQuestion: "Czy kaucja nie przekracza szczególnego limitu 6-krotności czynszu?",
      redCriteria: "Kaucja przekracza 6-krotność miesięcznego czynszu za dany lokal (sprzeczność z art. 19c ust. 1 UoPL).",
      yellowCriteria: "Kaucja przekracza 2-krotność miesięcznego czynszu.",
      greenCriteria: "Kaucja wynosi 1- lub 2-krotność miesięcznego czynszu, nie więcej niż 6-krotność.",
      missingIsRisk: false,
      missingSeverity: "none",
      benchmarkParam: "kaucja_wielokrotnosc_czynszu",
      kbSourceIds: ["uopl-art-19c"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-obowiazek-zgloszenia-us",
      contractType: "najem_okazjonalny",
      area: "Wymogi formalne najmu okazjonalnego",
      controlQuestion: "Czy umowa nakłada na wynajmującego obowiązek zgłoszenia do Urzędu Skarbowego?",
      redCriteria: "Zastrzeżenie zwalniające wynajmującego ze zgłoszenia umowy do naczelnika urzędu skarbowego.",
      yellowCriteria: "Brak potwierdzenia dla najemcy, że zgłoszenie do US zostało dokonane w terminie 14 dni.",
      greenCriteria: "Wynajmujący zobowiązuje się zgłosić zawarcie umowy naczelnikowi US w terminie 14 dni i przedstawić potwierdzenie najemcy na żądanie.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Niezgłoszenie umowy do US w terminie 14 dni skutkuje utratą uprawnień do szybkiej eksmisji (art. 19b ust. 2 UoPL).",
      kbSourceIds: ["uopl-art-19b"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-czas-oznaczony-limit-10-lat",
      contractType: "najem_okazjonalny",
      area: "Czas trwania i wypowiedzenie",
      controlQuestion: "Czy umowa została zawarta na czas oznaczony nieprzekraczający 10 lat?",
      redCriteria: "Umowa najmu okazjonalnego zawarta na czas nieoznaczony lub na okres powyżej 10 lat (sprzeczność z art. 19a ust. 1 UoPL).",
      yellowCriteria: "Czas trwania zbliżony do 10 lat bez sprecyzowania zasad przedłużenia.",
      greenCriteria: "Umowa zawarta na precyzyjnie oznaczony okres do 10 lat (zwykle 12 miesięcy) z możliwością jej aneksowania na kolejne okresy.",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Najem okazjonalny może być zawarty wyłącznie na czas oznaczony do 10 lat.",
      kbSourceIds: ["uopl-art-19a"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "okazjonalny-wylaczenie-przepisow-ochronnych",
      contractType: "najem_okazjonalny",
      area: "Prawa i obowiązki stron",
      controlQuestion: "Czy strony mają świadomość wyłączenia określonych przepisów ochronnych UoPL?",
      redCriteria: "Rozszerzenie wyłączeń przepisów UoPL ponad zakres przewidziany w art. 19e (np. wyłączenie art. 6a o obowiązkach wynajmującego).",
      yellowCriteria: "Brak pouczenia najemcy o wyłączeniu prawa do lokalu socjalnego i pomieszczenia tymczasowego.",
      greenCriteria: "Prawidłowe odwołanie do art. 19e UoPL z poszanowaniem pozostałych praw lokatora.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["uopl-art-19e"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
