import { ContractChecklist } from "./types";

/**
 * Checklista umowy deweloperskiej — szkic przygotowany przez /nowy-typ-umowy (etap 6).
 *
 * Podstawa: ustawa z 20 maja 2021 r. o ochronie praw nabywcy lokalu mieszkalnego lub domu
 * jednorodzinnego oraz Deweloperskim Funduszu Gwarancyjnym, tekst jednolity Dz.U. 2026 poz. 880
 * (stan prawny na 9 czerwca 2026 r.), jednostki legal-kb `dew-*`.
 *
 * Wszystkie punkty mają status "draft". Checklista NIE jest rejestrowana w
 * `ChecklistRegistry.registerDefaults()`: typ pozostaje nieaktywny w produkcji do zatwierdzenia
 * przez prawnika. Ewaluacja rejestruje ją jawnie przez `registerChecklist()`.
 */
export const checklistUmowaDeweloperska: ContractChecklist = {
  contractType: "umowa_deweloperska",
  title: "Checklista: umowa deweloperska (szkic do zatwierdzenia przez prawnika)",
  description:
    "Punkty kontrolne umowy deweloperskiej dla nabywcy będącego osobą fizyczną (art. 5 pkt 5 ustawy deweloperskiej), oparte na Dz.U. 2026 poz. 880.",
  version: "2026.10-draft",
  items: [
    {
      id: "dew-forma-aktu-notarialnego",
      contractType: "umowa_deweloperska",
      area: "Forma umowy",
      controlQuestion: "Czy umowa deweloperska jest zawierana w formie aktu notarialnego?",
      redCriteria: "Umowa ma być zawarta w zwykłej formie pisemnej albo bez udziału notariusza, mimo że art. 40 ust. 1 wymaga aktu notarialnego.",
      yellowCriteria: "Z dokumentu nie wynika, czy umowa będzie podpisana u notariusza (np. projekt bez oznaczenia aktu notarialnego).",
      greenCriteria: "Umowa jest aktem notarialnym albo jego projektem przygotowanym do podpisu u notariusza.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Ustawa wymaga, żeby umowę deweloperską zawrzeć w formie aktu notarialnego (art. 40 ust. 1).",
      kbSourceIds: ["dew-art-40"],
      amendmentTemplateId: "dew-forma-aktu-notarialnego",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-rachunek-powierniczy",
      contractType: "umowa_deweloperska",
      area: "Rachunek powierniczy",
      controlQuestion: "Czy wpłaty trafiają na mieszkaniowy rachunek powierniczy wskazany w umowie?",
      redCriteria: "Wpłaty mają trafiać na zwykły rachunek dewelopera, do kasy albo gotówką, a nie na mieszkaniowy rachunek powierniczy (art. 6 ust. 1, art. 8 ust. 1).",
      yellowCriteria: "Umowa wspomina rachunek powierniczy, ale nie podaje nazwy banku, numeru rachunku albo zasad dysponowania środkami (art. 35 ust. 1 pkt 10 lit. a).",
      greenCriteria: "Umowa wskazuje mieszkaniowy rachunek powierniczy z nazwą banku, numerem rachunku i zasadami dysponowania środkami.",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Rachunek powierniczy chroni twoje wpłaty. Umowa musi zawierać informacje o nim (art. 35 ust. 1 pkt 10).",
      kbSourceIds: ["dew-art-6", "dew-art-8", "dew-art-35"],
      amendmentTemplateId: "dew-rachunek-powierniczy",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-wplaty-wedlug-harmonogramu",
      contractType: "umowa_deweloperska",
      area: "Wpłaty według etapów budowy",
      controlQuestion: "Czy wpłaty zależą od zakończenia kolejnych etapów budowy z harmonogramu?",
      redCriteria: "Nabywca płaci całość lub większość ceny z góry, niezależnie od postępu budowy (art. 8 ust. 1–3).",
      yellowCriteria: "Harmonogram ma mniej niż cztery etapy albo koszt etapu wykracza poza 10–25% kosztów przedsięwzięcia (art. 24 ust. 2).",
      greenCriteria: "Wpłaty są rozłożone na etapy z harmonogramu i płatne po zakończeniu każdego etapu.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Umowa powinna określać wysokość, terminy i sposób wpłat zgodnie z etapami budowy (art. 35 ust. 1 pkt 9).",
      kbSourceIds: ["dew-art-8", "dew-art-24", "dew-art-35"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-koszty-rachunku-powierniczego",
      contractType: "umowa_deweloperska",
      area: "Koszty rachunku powierniczego",
      controlQuestion: "Czy koszty prowadzenia rachunku powierniczego ponosi deweloper?",
      redCriteria: "Umowa obciąża nabywcę kosztami, opłatami lub prowizjami za prowadzenie rachunku powierniczego (art. 14).",
      yellowCriteria: "Umowa nie mówi, kto ponosi koszty rachunku powierniczego.",
      greenCriteria: "Koszty, opłaty i prowizje za rachunek powierniczy ponosi deweloper.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-14"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-termin-przeniesienia-wlasnosci",
      contractType: "umowa_deweloperska",
      area: "Termin przeniesienia własności",
      controlQuestion: "Czy umowa podaje konkretny termin przeniesienia własności na nabywcę?",
      redCriteria: "Brak terminu albo termin zależny wyłącznie od woli dewelopera; umowa wymaga od nabywcy dłuższego terminu dodatkowego niż 120 dni przed odstąpieniem (art. 43 ust. 3).",
      yellowCriteria: "Termin jest podany, ale deweloper może go przesuwać bez zgody nabywcy.",
      greenCriteria: "Umowa podaje konkretną datę przeniesienia własności (art. 35 ust. 1 pkt 7).",
      missingIsRisk: true,
      missingSeverity: "red",
      missingExplanation: "Termin przeniesienia własności to obowiązkowy element umowy (art. 35 ust. 1 pkt 7). Jego brak daje prawo odstąpienia (art. 43 ust. 1 pkt 1).",
      kbSourceIds: ["dew-art-35", "dew-art-43"],
      amendmentTemplateId: "dew-termin-przeniesienia-wlasnosci",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-odbior-i-usuwanie-wad",
      contractType: "umowa_deweloperska",
      area: "Odbiór i usuwanie wad",
      controlQuestion: "Czy odbiór lokalu i terminy usuwania wad są zgodne z ustawą?",
      redCriteria: "Deweloper ma więcej niż 14 dni na odpowiedź na zgłoszone wady albo więcej niż 30 dni na ich usunięcie; odbiór bez obecności nabywcy (art. 41 ust. 2, 4, 6).",
      yellowCriteria: "Umowa nie opisuje procedury odbioru ani zgłaszania wad.",
      greenCriteria: "Odbiór w obecności nabywcy, protokół z wadami, odpowiedź w 14 dni i usunięcie wad w 30 dni.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Umowa powinna określać termin i sposób zawiadomienia o odbiorze oraz termin odbioru (art. 35 ust. 1 pkt 17).",
      kbSourceIds: ["dew-art-41", "dew-art-35", "dew-art-42"],
      amendmentTemplateId: "dew-odbior-i-usuwanie-wad",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-kary-i-odsetki",
      contractType: "umowa_deweloperska",
      area: "Kary umowne i odsetki",
      controlQuestion: "Czy odsetki należne deweloperowi nie są wyższe niż kary umowne należne nabywcy?",
      redCriteria: "Odsetki zastrzeżone dla dewelopera przewyższają kary umowne zastrzeżone dla nabywcy (art. 39 ust. 1).",
      yellowCriteria: "Umowa przewiduje odsetki dla dewelopera, ale nie przewiduje kar dla dewelopera za opóźnienie.",
      greenCriteria: "Kary umowne dla nabywcy są co najmniej tak wysokie jak odsetki dla dewelopera.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-39", "dew-art-35"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-odstapienie-nabywcy",
      contractType: "umowa_deweloperska",
      area: "Twoje prawo odstąpienia",
      controlQuestion: "Czy możesz odstąpić od umowy bez kosztów i potrąceń?",
      redCriteria: "Nabywca ma zapłacić za odstąpienie, ponieść jego koszty albo stracić część wpłat w sytuacjach z art. 43 ust. 1 (art. 44 ust. 1–2).",
      yellowCriteria: "Umowa nie opisuje warunków odstąpienia ani zwrotu wpłat (art. 35 ust. 1 pkt 13).",
      greenCriteria: "Umowa powtarza ustawowe przypadki odstąpienia i zasady zwrotu wpłat bez dodatkowych opłat.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Umowa powinna określać warunki odstąpienia i zwrotu wpłat (art. 35 ust. 1 pkt 13).",
      kbSourceIds: ["dew-art-43", "dew-art-44", "dew-art-42"],
      amendmentTemplateId: "dew-odstapienie-nabywcy",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-odstapienie-dewelopera",
      contractType: "umowa_deweloperska",
      area: "Odstąpienie przez dewelopera",
      controlQuestion: "Czy deweloper może odstąpić tylko w przypadkach i trybie z ustawy?",
      redCriteria: "Deweloper może odstąpić bez pisemnego wezwania z 30-dniowym terminem na zapłatę albo z powodów spoza art. 43 ust. 7–8.",
      yellowCriteria: "Umowa nie wyłącza odstąpienia, gdy opóźnienie wynika z siły wyższej.",
      greenCriteria: "Odstąpienie dewelopera tylko po pisemnym wezwaniu z 30-dniowym terminem albo po dwóch wezwaniach do odbioru w odstępie co najmniej 60 dni.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-43", "dew-art-42"],
      amendmentTemplateId: "dew-odstapienie-dewelopera",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-koszty-notarialne",
      contractType: "umowa_deweloperska",
      area: "Koszty notariusza i sądu",
      controlQuestion: "Czy koszty notariusza i sądu wieczystoksięgowego są dzielone po równo?",
      redCriteria: "Nabywca ponosi całość lub większość wynagrodzenia notariusza albo kosztów sądowych za umowę deweloperską (art. 40 ust. 2).",
      yellowCriteria: "Umowa nie mówi, kto ponosi koszty notariusza i sądu.",
      greenCriteria: "Koszty notariusza i sądu wieczystoksięgowego ponoszą deweloper i nabywca w równych częściach.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-40"],
      amendmentTemplateId: "dew-koszty-notarialne",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-prospekt-informacyjny",
      contractType: "umowa_deweloperska",
      area: "Prospekt informacyjny",
      controlQuestion: "Czy umowa zawiera oświadczenie, że otrzymałeś prospekt informacyjny z załącznikami?",
      redCriteria: "Umowa zawiera informacje sprzeczne z prospektem bez wyraźnego podkreślenia zmian (art. 35 ust. 2–3, art. 43 ust. 1 pkt 2).",
      yellowCriteria: "Brak oświadczenia o odbiorze prospektu i możliwości zapoznania się z dokumentami (art. 35 ust. 1 pkt 16).",
      greenCriteria: "Umowa zawiera oświadczenie o odbiorze prospektu z załącznikami; prospekt jest częścią umowy (art. 23 ust. 2).",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Prospekt jest częścią umowy. Deweloper musi go doręczyć przed jej zawarciem (art. 21 ust. 1, art. 23 ust. 2).",
      kbSourceIds: ["dew-art-21", "dew-art-23", "dew-art-35", "dew-art-43"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-zgoda-banku-na-bezobciazeniowe",
      contractType: "umowa_deweloperska",
      area: "Hipoteka banku dewelopera",
      controlQuestion: "Czy umowa informuje o zgodzie banku na przeniesienie własności bez hipoteki?",
      redCriteria: "Nieruchomość jest obciążona hipoteką, a umowa nie zawiera zgody banku ani zobowiązania do jej udzielenia (art. 25 ust. 1–2).",
      yellowCriteria: "Umowa wspomina zgodę banku, ale nie dołącza jej jako załącznika (art. 25 ust. 2).",
      greenCriteria: "Do umowy dołączono zgodę wierzyciela hipotecznego lub zobowiązanie do jej udzielenia albo nieruchomość nie ma hipoteki.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Umowa powinna zawierać informację o zgodzie banku albo zobowiązaniu do jej udzielenia (art. 35 ust. 1 pkt 18).",
      kbSourceIds: ["dew-art-25", "dew-art-35"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-cena-za-metr",
      contractType: "umowa_deweloperska",
      area: "Sposób określenia ceny",
      controlQuestion: "Czy cena jest podana jako powierzchnia użytkowa razy cena za metr kwadratowy?",
      redCriteria: "Umowa pozwala deweloperowi zmienić cenę jednostronnie, bez podstawy w umowie.",
      yellowCriteria: "Cena podana tylko ryczałtowo, bez ceny za 1 m² powierzchni użytkowej (art. 5a).",
      greenCriteria: "Cena to iloczyn powierzchni użytkowej i ceny za 1 m², a sposób pomiaru powierzchni jest wskazany (art. 5a, art. 35 ust. 1 pkt 15).",
      missingIsRisk: true,
      missingSeverity: "yellow",
      missingExplanation: "Cena musi być określona jako iloczyn metrów kwadratowych i ceny za 1 m² (art. 5a).",
      kbSourceIds: ["dew-art-5a", "dew-art-35"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-oplata-rezerwacyjna",
      contractType: "umowa_deweloperska",
      area: "Opłata rezerwacyjna",
      controlQuestion: "Czy opłata rezerwacyjna nie przekracza 1% ceny z prospektu informacyjnego?",
      redCriteria: "Opłata rezerwacyjna jest wyższa niż 1% ceny z prospektu (art. 32 ust. 2).",
      yellowCriteria: "Umowa nie informuje, czy zawarto umowę rezerwacyjną i jaka była opłata (art. 35 ust. 1 pkt 20).",
      greenCriteria: "Opłata rezerwacyjna nie przekracza 1% ceny i jest zaliczana na poczet ceny (art. 32 ust. 2–3).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-32", "dew-art-35"],
      amendmentTemplateId: "dew-oplata-rezerwacyjna",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "dew-postanowienia-mniej-korzystne",
      contractType: "umowa_deweloperska",
      area: "Zapisy gorsze niż ustawa",
      controlQuestion: "Czy umowa zawiera zapisy mniej korzystne dla nabywcy niż ustawa deweloperska?",
      redCriteria: "Zapis daje nabywcy mniej, niż przewiduje ustawa (np. dłuższe terminy dla dewelopera, dodatkowe opłaty). Taki zapis jest nieważny (art. 42).",
      yellowCriteria: "Zapis jest niejasny i można go czytać na niekorzyść nabywcy.",
      greenCriteria: "Umowa nie zawiera zapisów gorszych dla nabywcy niż przepisy ustawy.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["dew-art-42"],
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
