import { ContractChecklist } from "./types";

/**
 * Checklista Uniwersalna — weryfikowana dla KAŻDEJ analizowanej umowy w czypodpisac.pl.
 * Zgodnie ze skillem silnik-analizy (krok 4):
 * Obejmuje 18 uniwersalnych obszarów ryzyka prawnego w prawie umów.
 */
export const checklistUniwersalna: ContractChecklist = {
  contractType: "inna_nieznana",
  title: "Checklista Uniwersalna (każda umowa)",
  description: "Zestaw 18 uniwersalnych punktów kontrolnych sprawdzanych w każdej umowie cywilnoprawnej i konsumenckiej.",
  version: "2026.1",
  items: [
    {
      id: "uniwersalna-strony-i-reprezentacja",
      contractType: "inna_nieznana",
      area: "Strony i reprezentacja",
      controlQuestion: "Czy strony umowy są jednoznacznie zidentyfikowane i posiadają umocowanie do jej zawarcia?",
      redCriteria: "Brak wskazania PESEL/NIP/KRS, brak danych reprezentanta spółki, podpisanie przez osobę bez wykazanego pełnomocnictwa.",
      yellowCriteria: "Brak numeru dowodu tożsamości przy osobie fizycznej lub brak aktualnego odpisu KRS załączonego do umowy.",
      greenCriteria: "Pełne dane identyfikacyjne obu stron (PESEL, NIP, KRS, adresy), potwierdzone uprawnienie do reprezentacji.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-1"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-reprezentacja",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-forma-i-podpisy",
      contractType: "inna_nieznana",
      area: "Forma i podpisy",
      controlQuestion: "Czy umowa została sporządzona we właściwej formie (pisemna, elektroniczna kwalifikowana, notarialna)?",
      redCriteria: "Wymóg ustawowy formy szczególnej pod rygorem nieważności (np. najem okazjonalny u notariusza, zbycie nieruchomości) zastąpiony zwykłym mailem.",
      yellowCriteria: "Brak określenia sposobu składania oświadczeń woli i formy aneksowania (brak rygoru nieważności dla zmian).",
      greenCriteria: "Prawidłowa forma (własnoręczny podpis lub kwalifikowany podpis elektroniczny), klauzula aneksowania na piśmie pod rygorem nieważności.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-660"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-forma",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-przedmiot-i-swiadczenia",
      contractType: "inna_nieznana",
      area: "Przedmiot i świadczenia",
      controlQuestion: "Czy zakres obowiązków, przedmiot umowy i standard wykonania są precyzyjnie określone?",
      redCriteria: "Jednostronne prawo kontrahenta do dowolnej modyfikacji zakresu świadczenia bez zgody użytkownika.",
      yellowCriteria: "Ogólnikowy opis przedmiotu umowy, brak mierzalnych kryteriów odbioru lub parametrów technicznych.",
      greenCriteria: "Szczegółowy i wyczerpujący opis świadczeń obu stron oraz procedura zgłaszania zastrzeżeń i odbioru.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["2487"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-przedmiot",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-cena-waloryzacja-odsetki",
      contractType: "inna_nieznana",
      area: "Cena, waloryzacja, odsetki",
      controlQuestion: "Czy kwota wynagrodzenia/czynszu, mechanizm waloryzacji i odsetki są precyzyjne i symetryczne?",
      redCriteria: "Ukryte opłaty manipulacyjne, odsetki przekraczające odsetki maksymalne, prawo do podwyżki bez wskazania kryteriów obiektywnych.",
      yellowCriteria: "Brak sprecyzowania, czy kwota jest netto czy brutto, brak terminu płatności lub numeru rachunku bankowego.",
      greenCriteria: "Jednoznaczna kwota brutto, przejrzysty termin płatności, odsetki ustawowe, waloryzacja wyłącznie wg wskaźnika GUS.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["2487"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-cena",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-terminy-i-harmonogram",
      contractType: "inna_nieznana",
      area: "Terminy i harmonogram",
      controlQuestion: "Czy terminy realizacji świadczeń są sztywne i wiążą obie strony symetrycznie?",
      redCriteria: "Jednostronne prawo kontrahenta do przedłużania terminu realizacji bez konsekwencji i bez prawa odstąpienia przez użytkownika.",
      yellowCriteria: "Termin określony niejednoznacznie (np. 'w rozsądnym terminie', 'niezwłocznie po uzyskaniu dokumentów').",
      greenCriteria: "Konkretne daty kalendarzowe lub precyzyjnie określone dni robocze z procedurą odbioru.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-3"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-terminy",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-jednostronna-zmiana",
      contractType: "inna_nieznana",
      area: "Jednostronna zmiana umowy lub ceny",
      controlQuestion: "Czy umowa wyklucza arbitralną, jednostronną zmianę warunków lub cennika przez drugą stronę?",
      redCriteria: "Zapis uprawniający kontrahenta do jednostronnej zmiany umowy lub regulaminu bez ważnej przyczyny i bez prawa natychmiastowego wypowiedzenia.",
      yellowCriteria: "Prawo zmiany cennika z lakonicznym katalogiem przyczyn zewnętrznych bez gwarancji zachowania dotychczasowej ceny dla zamówionych usług.",
      greenCriteria: "Wszelkie zmiany umowy wymagają obustronnego aneksu w formie pisemnej pod rygorem nieważności.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["2487"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-zmiana-umowy",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-automatyczne-przedluzenie",
      contractType: "inna_nieznana",
      area: "Automatyczne przedłużenie",
      controlQuestion: "Czy umowa nie przedłuża się automatycznie na czas określony bez wyraźnej zgody konsumenta?",
      redCriteria: "Automatyczne odnowienie umowy na kolejny okres oznaczony (np. 12 lub 24 miesiące) w przypadku braku sprzeciwu w nierealistycznie krótkim terminie.",
      yellowCriteria: "Przedłużenie na czas nieoznaczony z długim okresem wypowiedzenia (powyżej 3 miesięcy).",
      greenCriteria: "Umowa kończy się z upływem terminu lub przechodzi w czas nieoznaczony z 1-miesięcznym okresem wypowiedzenia.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-3"],
      uokikClauseNumbers: ["592"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-przedluzenie",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-wypowiedzenie-i-odstapienie",
      contractType: "inna_nieznana",
      area: "Wypowiedzenie i odstąpienie",
      controlQuestion: "Czy przesłanki i terminy wypowiedzenia oraz odstąpienia są symetryczne i zgodne z przepisami bezwzględnymi?",
      redCriteria: "Brak prawa wypowiedzenia dla użytkownika przy jednoczesnym przyznaniu go drugiej stronie; natychmiastowe rozwiązanie z błahego powodu.",
      yellowCriteria: "Długi okres wypowiedzenia (np. 6 miesięcy) krępujący swobodę działalności konsumenta lub najemcy.",
      greenCriteria: "Równy okres wypowiedzenia dla obu stron, zamknięty katalog ważnych przyczyn, prawo odstąpienia w razie zwłoki.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-673", "kc-art-385-1"],
      uokikClauseNumbers: ["6124"],
      courtRulingSignatures: ["sn-iii-czp-11-13"],
      amendmentTemplateId: "poprawka-uniwersalna-wypowiedzenie",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-kary-umowne-i-limity",
      contractType: "inna_nieznana",
      area: "Kary umowne i ich górne granice",
      controlQuestion: "Czy kary umowne są symetryczne, ograniczone górnym pułapem (cap) i nie są rażąco wygórowane?",
      redCriteria: "Kara umowna za samo skorzystanie z prawa do wypowiedzenia umowy; kara za opóźnienie w zapłacie pieniężnej; rażąco wygórowane kwoty bez górnego limitu.",
      yellowCriteria: "Kara umowna jednostronna (zastrzeżona wyłącznie na rzecz kontrahenta), brak maksymalnego limitu (cap).",
      greenCriteria: "Symetryczne kary umowne, precyzyjne przesłanki naliczenia, górny limit odpowiedzialności (np. maks. 10-20% wartości umowy).",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["2045"],
      courtRulingSignatures: ["sn-v-csk-31-08"],
      amendmentTemplateId: "poprawka-uniwersalna-kary",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-ograniczenia-odpowiedzialnosci",
      contractType: "inna_nieznana",
      area: "Ograniczenia odpowiedzialności",
      controlQuestion: "Czy umowa nie wyłącza bezprawnie odpowiedzialności kontrahenta za szkody wyrządzone z winy umyślnej lub rażącego niedbalstwa?",
      redCriteria: "Całkowite wyłączenie odpowiedzialności kontrahenta za niewykonanie umowy lub szkody na osobie/mieniu konsumenta.",
      yellowCriteria: "Wyłączenie odpowiedzialności za utracone korzyści w relacji B2B bez symetrycznego ograniczenia dla drugiej strony.",
      greenCriteria: "Standardowa odpowiedzialność na zasadach ogólnych Kodeksu cywilnego z poszanowaniem art. 473 § 2 k.c.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["6124"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-odpowiedzialnosc",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-zabezpieczenia-platnosci",
      contractType: "inna_nieznana",
      area: "Zabezpieczenia (weksel, kaucja, poddanie egzekucji)",
      controlQuestion: "Czy zabezpieczenia są proporcjonalne, nie dublują się i posiadają precyzyjne zasady rozliczenia i zwrotu?",
      redCriteria: "Weksel in blanco bez deklaracji wekslowej od konsumenta; zatrzymanie całości kaucji za drobne usterki wynikające ze zwykłego zużycia.",
      yellowCriteria: "Wielość zabezpieczeń (kaucja + poręczenie + poddanie egzekucji) nieproporcjonalna do wartości umowy.",
      greenCriteria: "Pojedyncze, proporcjonalne zabezpieczenie z jasną procedurą zwrotu w terminie do 14-30 dni po zakończeniu umowy.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "uopl-art-6"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-zabezpieczenie",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-cesja-i-przeniesienie-praw",
      contractType: "inna_nieznana",
      area: "Cesja i przeniesienie praw",
      controlQuestion: "Czy kontrahent nie zastrzegł sobie prawa do przeniesienia praw i obowiązków z umowy na podmiot trzeci bez zgody użytkownika?",
      redCriteria: "Zgoda in blanco na przeniesienie długu lub praw z umowy na dowolną spółkę powiązaną kontrahenta.",
      yellowCriteria: "Zakaz cesji wierzytelności użytkownika przy jednoczesnym braku zakazu dla kontrahenta.",
      greenCriteria: "Przeniesienie praw lub obowiązków wymaga uprzedniej pisemnej zgody obu stron umowy.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-3"],
      uokikClauseNumbers: ["4991"],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-cesja",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-poufnosc-i-zakaz-konkurencji",
      contractType: "inna_nieznana",
      area: "Poufność i zakaz konkurencji",
      controlQuestion: "Czy klauzule poufności i zakazu konkurencji są symetryczne, ograniczone w czasie i posiadają wynagrodzenie?",
      redCriteria: "Nieodpłatny zakaz konkurencji po ustaniu umowy cywilnoprawnej lub nieograniczona w czasie bezwzględna poufność z wysokimi karami.",
      yellowCriteria: "Zbyt szeroka definicja informacji poufnych obejmująca wiedzę powszechnie dostępną.",
      greenCriteria: "Poufność ograniczona do 1-2 lat po zakończeniu współpracy, wyraźne wyłączenia, brak nieodpłatnego zakazu konkurencji.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kp-art-101-1"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-poufnosc",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-dane-osobowe-rodo",
      contractType: "inna_nieznana",
      area: "Dane osobowe (RODO)",
      controlQuestion: "Czy umowa zawiera prawidłową klauzulę informacyjną RODO i nie wymusza zgód marketingowych jako warunku umowy?",
      redCriteria: "Wymuszenie zgody na marketing lub udostępnienie danych podmiotom trzecim jako warunek zawarcia umowy z konsumentem.",
      yellowCriteria: "Brak klauzuli informacyjnej z art. 13/14 RODO lub brak umowy powierzenia przetwarzania danych w relacji B2B.",
      greenCriteria: "Kompletna klauzula informacyjna RODO, dobrowolność zgód marketingowych, właściwa umowa powierzenia (DPA).",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-1"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-rodo",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-sad-i-zapis-polubowny",
      contractType: "inna_nieznana",
      area: "Właściwość sądu i zapis na sąd polubowny",
      controlQuestion: "Czy umowa nie narzuca konsumentowi odległego sądu powszechnego lub kosztownego sądu polubownego?",
      redCriteria: "Narzucenie konsumentowi sądu właściwego dla siedziby kontrahenta (np. 400 km dalej) lub narzucenie sądu polubownego (arbitrażu).",
      yellowCriteria: "W umowie B2B: brak wskazania właściwości sądu, co wymusza stosowanie ogólnych reguł k.p.c.",
      greenCriteria: "W umowach z konsumentami: brak zapisu narzucającego sąd (właściwość wg miejsca zamieszkania konsumenta) lub wyraźny wybór sądu konsumenta.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-3"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-sad",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-prawo-wlasciwe",
      contractType: "inna_nieznana",
      area: "Prawo właściwe",
      controlQuestion: "Czy umowa podlega prawu polskiemu i jurysdykcji polskich sądów?",
      redCriteria: "Wybór prawa obcego pozbawiający konsumenta ochrony wynikającej z bezwzględnie obowiązujących przepisów prawa polskiego.",
      yellowCriteria: "Brak wskazania prawa właściwego w umowie międzynarodowej.",
      greenCriteria: "Wskazanie prawa polskiego jako właściwego dla wykonania i interpretacji umowy.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-prawo",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-wzorce-umowne-owu",
      contractType: "inna_nieznana",
      area: "Wzorce umowne (regulaminy, OWU)",
      controlQuestion: "Czy wzorce umowne powoływane w treści umowy zostały doręczone przed jej zawarciem?",
      redCriteria: "Oświadczenie o akceptacji regulaminu lub OWU, które nie zostały fizycznie lub elektronicznie doręczone użytkownikowi przed podpisaniem.",
      yellowCriteria: "Odesłanie do regulaminu dostępnego wyłącznie na stronie WWW z prawem do jego dowolnej zmiany.",
      greenCriteria: "Wszystkie załączniki i OWU stanowią integralną część umowy i zostały fizycznie załączone lub doręczone przed podpisaniem.",
      missingIsRisk: true,
      missingSeverity: "yellow",
      kbSourceIds: ["kc-art-385-1"],
      uokikClauseNumbers: [],
      courtRulingSignatures: [],
      amendmentTemplateId: "poprawka-uniwersalna-wzorce",
      lawyerReviewStatus: "draft",
      version: 1,
    },
    {
      id: "uniwersalna-klauzule-abuzywne-katalog",
      contractType: "inna_nieznana",
      area: "Klauzule potencjalnie abuzywne (art. 385³ k.c.)",
      controlQuestion: "Czy umowa nie zawiera postanowień z 'szarej listy' klauzul niedozwolonych (art. 385³ k.c.)?",
      redCriteria: "Zapis wyłączający obowiązek zwrotu wpłaconych kwot przy niewykonaniu umowy, uzależnienie zwrotu zaliczki od woli kontrahenta, domniemanie złożenia oświadczenia woli.",
      yellowCriteria: "Niejednoznaczne sformułowania interpretowane przez drugą stronę na swoją korzyść.",
      greenCriteria: "Brak jakichkolwiek zapisów zbieżnych z katalogiem art. 385³ k.c. oraz rejestrem klauzul niedozwolonych UOKiK.",
      missingIsRisk: false,
      missingSeverity: "none",
      kbSourceIds: ["kc-art-385-1", "kc-art-385-3"],
      uokikClauseNumbers: ["6124", "2487", "2045"],
      courtRulingSignatures: ["tsue-c-229-19", "sn-iii-czp-52-19"],
      amendmentTemplateId: "poprawka-uniwersalna-abuzywne",
      lawyerReviewStatus: "draft",
      version: 1,
    },
  ],
};
