/**
 * Rejestr 18 aktów prawnych tworzących WARSTWĘ A (RDZEŃ) bazy legal-kb.
 * Zgodnie z regułą 02-prawo-zrodla-aktualnosc.md:
 * Akty te podlegają ciągłemu, automatycznemu monitorowaniu przez API Sejmu ELI.
 */

export interface CoreActDefinition {
  id: string;
  title: string;
  shortTitle: string;
  baseEliId: string; // np. "DU/1964/93"
  latestKnownUnifiedEli?: string; // np. "DU/2023/1610"
  officialPublisher: string;
  coverageScope: "full" | "tenancy_and_civil_contracts" | "qualification_only" | "procedural";
  contractTypeTags: string[];
  notes?: string;
}

export const CORE_ACTS_REGISTRY: CoreActDefinition[] = [
  {
    id: "kc",
    title: "Ustawa z dnia 23 kwietnia 1964 r. — Kodeks cywilny",
    shortTitle: "Kodeks cywilny",
    baseEliId: "DU/1964/93",
    latestKnownUnifiedEli: "DU/2023/1610",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: [
      "ogolne",
      "najem_lokalu_mieszkalnego",
      "najem_lokalu_uzytkowego",
      "najem_okazjonalny",
      "najem_instytucjonalny",
      "dzielo",
      "zlecenie",
      "b2b_uslugi_freelancer",
      "konsument",
    ],
    notes: "Fundament całego prawa umów, w tym klauzule abuzywne (art. 385¹-385⁵) i najem (art. 659-692).",
  },
  {
    id: "uopl",
    title: "Ustawa z dnia 21 czerwca 2001 r. o ochronie praw lokatorów, mieszkaniowym zasobie gminy i o zmianie Kodeksu cywilnego",
    shortTitle: "Ustawa o ochronie praw lokatorów",
    baseEliId: "DU/2001/733",
    latestKnownUnifiedEli: "DU/2023/725",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: [
      "najem_lokalu_mieszkalnego",
      "najem_okazjonalny",
      "najem_instytucjonalny",
      "konsument",
    ],
    notes: "Lex specialis dla najmu lokali mieszkalnych (kaucje, wypowiedzenia, podwyżki czynszu).",
  },
  {
    id: "uokik-konsument",
    title: "Ustawa z dnia 30 maja 2014 r. o prawach konsumenta",
    shortTitle: "Ustawa o prawach konsumenta",
    baseEliId: "DU/2014/827",
    latestKnownUnifiedEli: "DU/2023/2759",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["konsument", "umowa_na_odleglosc", "b2b_uslugi_freelancer"],
    notes: "Odstąpienie od umowy, obowiązki informacyjne, umowy zawierane poza lokalem przedsiębiorstwa.",
  },
  {
    id: "deweloperska",
    title: "Ustawa z dnia 20 maja 2021 r. o ochronie praw nabywcy lokalu mieszkalnego lub domu jednorodzinnego oraz Deweloperskim Funduszu Gwarancyjnym",
    shortTitle: "Ustawa deweloperska",
    baseEliId: "DU/2021/1177",
    latestKnownUnifiedEli: "DU/2026/880",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["umowa_deweloperska", "umowa_rezerwacyjna", "umowa_przedwstepna", "konsument"],
    notes: "Rachunki powiernicze, DFG, harmonogram płatności, odbiór techniczny, wady.",
  },
  {
    id: "kredyt-konsumencki",
    title: "Ustawa z dnia 12 maja 2011 r. o kredycie konsumenckim",
    shortTitle: "Ustawa o kredycie konsumenckim",
    baseEliId: "DU/2011/540",
    latestKnownUnifiedEli: "DU/2023/1028",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["kredyt_konsumencki", "pozyczka", "konsument"],
    notes: "RRSO, maksymalne pozaodsetkowe koszty kredytu (art. 36a), wcześniejsza spłata.",
  },
  {
    id: "kredyt-hipoteczny",
    title: "Ustawa z dnia 23 marca 2017 r. o kredycie hipotecznym oraz o nadzorze nad pośrednikami kredytu hipotecznego i agentami",
    shortTitle: "Ustawa o kredycie hipotecznym",
    baseEliId: "DU/2017/819",
    latestKnownUnifiedEli: "DU/2022/2245",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["kredyt_hipoteczny", "konsument"],
    notes: "Ocena zdolności kredytowej, prowizje za wcześniejszą spłatę, wskaźniki referencyjne (WIBOR/WIRON).",
  },
  {
    id: "zatory-platnicze",
    title: "Ustawa z dnia 8 marca 2013 r. o przeciwdziałaniu nadmiernym opóźnieniom w transakcjach handlowych",
    shortTitle: "Ustawa o zatorach płatniczych",
    baseEliId: "DU/2013/403",
    latestKnownUnifiedEli: "DU/2023/1790",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["b2b_uslugi_freelancer", "najem_lokalu_uzytkowego", "dzielo", "zlecenie"],
    notes: "Maksymalne terminy płatności (60 dni), odsetki ustawowe za opóźnienie w transakcjach handlowych, rekompensata 40/70/100 EUR.",
  },
  {
    id: "prawo-autorskie",
    title: "Ustawa z dnia 4 lutego 1994 r. o prawie autorskim i prawach pokrewnych",
    shortTitle: "Ustawa o prawie autorskim",
    baseEliId: "DU/1994/83",
    latestKnownUnifiedEli: "DU/2022/2509",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["b2b_uslugi_freelancer", "dzielo", "prawa_autorskie"],
    notes: "Pola eksploatacji (art. 41, 50), autorskie prawa zależne i osobiste, wynagrodzenie.",
  },
  {
    id: "kp",
    title: "Ustawa z dnia 26 czerwca 1974 r. — Kodeks pracy",
    shortTitle: "Kodeks pracy",
    baseEliId: "DU/1974/141",
    latestKnownUnifiedEli: "DU/2023/1465",
    officialPublisher: "DU",
    coverageScope: "qualification_only",
    contractTypeTags: ["umowa_o_prace", "zlecenie", "b2b_uslugi_freelancer"],
    notes: "Kwalifikacja stosunku pracy (art. 22 § 1-1²), zakaz zastępowania umów o pracę umowami cywilnoprawnymi.",
  },
  {
    id: "ubezpieczeniowa",
    title: "Ustawa z dnia 11 września 2015 r. o działalności ubezpieczeniowej i reasekuracyjnej",
    shortTitle: "Ustawa o działalności ubezpieczeniowej",
    baseEliId: "DU/2015/1844",
    latestKnownUnifiedEli: "DU/2024/839",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["owu_ubezpieczenie", "konsument"],
    notes: "Przejrzystość OWU, postanowienia niejednoznaczne na korzyść ubezpieczającego.",
  },
  {
    id: "uslugi-platnicze",
    title: "Ustawa z dnia 19 sierpnia 2011 r. o usługach płatniczych",
    shortTitle: "Ustawa o usługach płatniczych",
    baseEliId: "DU/2011/1146",
    latestKnownUnifiedEli: "DU/2024/30",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["uslugi_finansowe", "konsument"],
    notes: "Umowy ramowe rachunków i kart, opłaty, transakcje nieautoryzowane (chargeback).",
  },
  {
    id: "pke",
    title: "Ustawa z dnia 12 lipca 2024 r. — Prawo komunikacji elektronicznej",
    shortTitle: "Prawo komunikacji elektronicznej",
    baseEliId: "DU/2024/1221",
    latestKnownUnifiedEli: undefined,
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["telekomunikacyjna", "konsument"],
    notes: "Nowe prawo telekomunikacyjne (zastąpiło Prawo telekomunikacyjne z 2004 r.).",
  },
  {
    id: "uslugi-turystyczne",
    title: "Ustawa z dnia 24 listopada 2017 r. o imprezach turystycznych i powiązanych usługach turystycznych",
    shortTitle: "Ustawa o imprezach turystycznych",
    baseEliId: "DU/2017/2361",
    latestKnownUnifiedEli: "DU/2023/2211",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["turystyka", "konsument"],
    notes: "TFG, odstąpienie z powodu nadzwyczajnych okoliczności, odszkodowanie i zadośćuczynienie za zmarnowany urlop.",
  },
  {
    id: "prawo-energetyczne",
    title: "Ustawa z dnia 10 kwietnia 1997 r. — Prawo energetyczne",
    shortTitle: "Prawo energetyczne",
    baseEliId: "DU/1997/358",
    latestKnownUnifiedEli: "DU/2024/266",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["energia", "gaz", "konsument"],
    notes: "Umowy kompleksowe, standardy jakościowe obsługi, zmiana sprzedawcy, taryfy URE.",
  },
  {
    id: "rodo-uodo",
    title: "Ustawa z dnia 10 maja 2018 r. o ochronie danych osobowych",
    shortTitle: "Ustawa o ochronie danych osobowych / RODO",
    baseEliId: "DU/2018/1000",
    latestKnownUnifiedEli: "DU/2019/1781",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["ogolne", "rodo", "dane_osobowe"],
    notes: "Klauzule powierzenia przetwarzania danych osobowych (art. 28 RODO) w umowach B2B.",
  },
  {
    id: "ksh",
    title: "Ustawa z dnia 15 września 2000 r. — Kodeks spółek handlowych",
    shortTitle: "Kodeks spółek handlowych",
    baseEliId: "DU/2000/1037",
    latestKnownUnifiedEli: "DU/2024/18",
    officialPublisher: "DU",
    coverageScope: "full",
    contractTypeTags: ["spolki", "umowa_spolki_zoo", "umowa_spolki_cywilnej"],
    notes: "Umowy spółek z o.o., jawnych, komandytowych; reprezentacja spółek (art. 205 KSH).",
  },
  {
    id: "kpc",
    title: "Ustawa z dnia 17 listopada 1964 r. — Kodeks postępowania cywilnego",
    shortTitle: "Kodeks postępowania cywilnego",
    baseEliId: "DU/1964/296",
    latestKnownUnifiedEli: "DU/2023/1550",
    officialPublisher: "DU",
    coverageScope: "procedural",
    contractTypeTags: ["ogolne", "wlasciwosc_sadu", "zapis_na_sad_polubowny", "konsument"],
    notes: "Właściwość sądu (art. 46 KPC — zakaz narzucania właściwości konsumentowi), zapis na sąd polubowny.",
  },
];
